apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bke-monitor-victoria-metrics-agent
  namespace: bke-cluster-log
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bke-monitor-victoria-metrics-agent
subjects:
  - kind: ServiceAccount
    name: bke-monitor-victoria-metrics-agent
    namespace: bke-cluster-log

