apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: bke-monitor
    app.kubernetes.io/name: victoria-metrics-agent
  name: bke-monitor-victoria-metrics-agent
  namespace: bke-cluster-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bke-monitor
      app.kubernetes.io/name: victoria-metrics-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bke-monitor
        app.kubernetes.io/name: victoria-metrics-agent
    spec:
      containers:
      - args:
        - -promscrape.config=/config/scrape.yml
        - -remoteWrite.tmpDataPath=/tmpData
        - -remoteWrite.url={{ .Values.mimir_url }}
        - -remoteWrite.bearerToken={{ .Values.mimir_bearer_token }}
        - -remoteWrite.label=cluster={{ .Values.cluster_name }}
        - -envflag.enable=true
        - -envflag.prefix=VM_
        - -loggerFormat=json
        image: victoriametrics/vmagent:v1.101.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 5
        name: victoria-metrics-agent
        ports:
        - containerPort: 8429
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmpData
          name: tmpdata
        - mountPath: /config
          name: config
        workingDir: /
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bke-monitor-victoria-metrics-agent
      serviceAccountName: bke-monitor-victoria-metrics-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmpdata
      - configMap:
          defaultMode: 420
          name: bke-monitor-victoria-metrics-agent-config
        name: config
