apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: bke-monitor
    app.kubernetes.io/name: bke-monitor-victoria-metrics-agent
  name: bke-monitor-victoria-metrics-agent
  namespace: bke-cluster-metrics
