apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: bke-monitor
  labels:
    app.kubernetes.io/instance: bke-monitor
    app.kubernetes.io/name:  bke-monitor-kube-state-metrics
  name: bke-monitor-kube-state-metrics
  namespace: bke-obs-stack
