apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: bke-monitor
  name: bke-monitor-prometheus-node-exporter
  namespace: bke-cluster-log
