apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: bke-monitor
    app.kubernetes.io/name: kube-state-metrics
  name: bke-monitor-kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bke-monitor-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: bke-monitor-kube-state-metrics
  namespace: bke-cluster-log