apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: bke-monitor
    app.kubernetes.io/name: promtail
  name: bke-monitor-promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bke-monitor-promtail
subjects:
- kind: ServiceAccount
  name: bke-monitor-promtail
  namespace: bke-cluster-log
